### Pycaret? (파이캐롯?)

- Python의 오픈 소스 라이브러리
- 머신러닝의 워크플로우를 자동화 처리(AutoML)
- 코딩, 전처리, 모델 선택, 파라미터 튜닝 작업을 자동으로 진행

# Pycaret install(파이캐롯 설치)
- Pycaret을 사용하기 위해 설치한다.

In [ ]:
!pip install pycaret

Requirement already satisfied: pycaret in /usr/local/lib/python3.7/dist-packages (2.3.6)
Requirement already satisfied: pandas-profiling>=2.8.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.1.1)
Requirement already satisfied: lightgbm>=2.3.1 in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.3.2)
Requirement already satisfied: kmodes>=0.10.1 in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.11.1)
Requirement already satisfied: imbalanced-learn==0.7.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.7.0)
Requirement already satisfied: scipy<=1.5.4 in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.5.4)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.1.0)
Requirement already satisfied: yellowbrick>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.3.post1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.11.2)
Requirement already satisfied: cufflinks>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.17.3)
Requirement already satisfied: gensim<4.0.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.6.0)
Requirement already satisfied: IPython in /usr/local/lib/python3.7/dist-packages (from pycaret) (7.31.1)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.5.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.2.5)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.7/dist-packages (from pycaret) (7.6.5)
Requirement already satisfied: umap-learn in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.5.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.5.1)
Requirement already satisfied: textblob in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.15.3)
Requirement already satisfied: scikit-learn==0.23.2 in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.23.2)
Requirement already satisfied: scikit-plot in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.3.7)
Requirement already satisfied: pyLDAvis in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.2.2)
Requirement already satisfied: mlxtend>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.19.0)
Requirement already satisfied: Boruta in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.3)
Requirement already satisfied: pyod in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.9.7)
Requirement already satisfied: plotly>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from pycaret) (5.5.0)
Requirement already satisfied: pyyaml<6.0.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (5.4.1)
Requirement already satisfied: spacy<2.4.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (2.2.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.3.5)
Requirement already satisfied: mlflow in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.23.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn==0.7.0->pycaret) (1.19.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.23.2->pycaret) (3.0.0)
Requirement already satisfied: setuptools>=34.4.1 in /usr/local/lib/python3.7/dist-packages (from cufflinks>=0.17.0->pycaret) (57.4.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from cufflinks>=0.17.0->pycaret) (1.15.0)
Requirement already satisfied: colorlover>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from cufflinks>=0.17.0->pycaret) (0.3.0)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from gensim<4.0.0->pycaret) (5.2.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (0.2.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (4.4.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (0.18.1)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (2.6.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (0.7.5)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (0.1.3)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (3.0.26)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (6.8.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (1.0.2)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (5.1.3)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (3.5.2)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (0.2.0)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (1.0.0)
Requirement already satisfied: jupyter-client<8.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (5.3.5)
Requirement already satisfied: tornado<7.0,>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (5.1.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (1.5.4)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.16->IPython->pycaret) (0.8.3)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->pycaret) (4.9.1)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->pycaret) (22.3.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->pycaret) (2.8.2)
Requirement already satisfied: wheel in /usr/local/lib/python3.7/dist-packages (from lightgbm>=2.3.1->pycaret) (0.37.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (4.29.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (3.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (7.1.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (4.3.3)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (5.4.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (3.10.0.2)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (21.4.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (4.10.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (0.18.1)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (3.7.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pycaret) (2018.9)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (2.11.3)
Requirement already satisfied: pydantic>=1.8.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (1.9.0)
Requirement already satisfied: visions[type_image_path]==0.7.4 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (0.7.4)
Requirement already satisfied: htmlmin>=0.1.12 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (0.1.12)
Requirement already satisfied: phik>=0.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (0.12.0)
Requirement already satisfied: requests>=2.24.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (2.27.1)
Requirement already satisfied: missingno>=0.4.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (0.5.0)
Requirement already satisfied: markupsafe~=2.0.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (2.0.1)
Requirement already satisfied: tqdm>=4.48.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (4.62.3)
Requirement already satisfied: multimethod>=1.4 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (1.7)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (0.2.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (2.6.3)
Requirement already satisfied: imagehash in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (4.2.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect>4.3->IPython->pycaret) (0.7.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly>=4.4.1->pycaret) (8.0.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->pycaret) (0.2.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.0.11)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2021.10.8)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (2.0.6)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.0.5)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (0.9.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (3.0.6)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.1.3)
Requirement already satisfied: thinc==7.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (7.4.0)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.0.0)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (0.4.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.0.6)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets->pycaret) (5.3.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.8.0)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.13.1)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (5.6.1)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.7/dist-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (1.2.0)
Requirement already satisfied: databricks-cli>=0.8.7 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (0.16.2)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.3.0)
Requirement already satisfied: Flask in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.1.4)
Requirement already satisfied: prometheus-flask-exporter in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (0.18.7)
Requirement already satisfied: sqlparse>=0.3.1 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (0.4.2)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (7.1.2)
Requirement already satisfied: querystring-parser in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.2.4)
Requirement already satisfied: docker>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (5.0.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.4.31)
Requirement already satisfied: gunicorn in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (20.1.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (0.3)
Requirement already satisfied: gitpython>=2.1.0 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (3.1.26)
Requirement already satisfied: alembic in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.7.6)
Requirement already satisfied: protobuf>=3.7.0 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (3.17.3)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.7/dist-packages (from databricks-cli>=0.8.7->mlflow->pycaret) (0.8.9)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python3.7/dist-packages (from docker>=4.0.0->mlflow->pycaret) (1.2.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.7/dist-packages (from gitpython>=2.1.0->mlflow->pycaret) (4.0.9)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.7/dist-packages (from gitdb<5,>=4.0.1->gitpython>=2.1.0->mlflow->pycaret) (5.0.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.7/dist-packages (from alembic->mlflow->pycaret) (1.1.6)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->mlflow->pycaret) (1.1.2)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask->mlflow->pycaret) (1.0.1)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask->mlflow->pycaret) (1.1.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.8.4)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.7.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (4.1.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.7/dist-packages (from prometheus-flask-exporter->mlflow->pycaret) (0.13.1)
Requirement already satisfied: funcy in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (1.17)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (0.16.0)
Requirement already satisfied: numexpr in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (2.8.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.7/dist-packages (from pyod->pycaret) (0.13.1)
Requirement already satisfied: numba>=0.35 in /usr/local/lib/python3.7/dist-packages (from pyod->pycaret) (0.51.2)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.7/dist-packages (from numba>=0.35->pyod->pycaret) (0.34.0)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.7/dist-packages (from statsmodels->pyod->pycaret) (0.5.2)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.7/dist-packages (from umap-learn->pycaret) (0.5.6)

'bubbleplot' 그래프를 사용하기 위해 설치해준다.

<'Bubbly' 패키지에 대해>

Bubbly는 Plotly를 사용하여 대화형 및 애니메이션 거품 차트를

그리기 위한 패키지입니다. 애니메이션 거품형 차트는 총 7개의 

변수를 수용할 수 있습니다. 

X축, Y축, Z축, 시간, 거품, 크기 및 색상을 컴팩트하고 매혹적인

방식으로 보여줍니다. Bubbly는 다양한 사용자 정의로 사용하기

쉽고 특히 Jupyter 노트북에서 사용하기에 적합하며 Kaggle 커널과

같은 plotly의 오프라인 모드에서 작동하도록 설계되었습니다.

In [ ]:
pip install bubbly

Requirement already satisfied: bubbly in /usr/local/lib/python3.7/dist-packages (1.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from bubbly) (1.3.5)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from bubbly) (5.5.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->bubbly) (1.19.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->bubbly) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->bubbly) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->bubbly) (1.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->bubbly) (8.0.1)

'bubbleplot' 그래프를 사용하기 위해 'chart_studio' 패키지도

 설치해준다.

 <'chart_studio' 패키지에 대해>

 'chart_studio'는 'plotly'를 사용하여 그래프를 그리기 위한 
 
  웹 서비스를 제공한다.

 import chart_studio.plotly as py

 import plotly.graph_objects as go
 
 이렇게 사용하면 선 그래프와 산점도 그래프를 나타낼수도 있다.

In [ ]:
pip install chart_studio

Requirement already satisfied: chart_studio in /usr/local/lib/python3.7/dist-packages (1.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from chart_studio) (2.27.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from chart_studio) (5.5.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from chart_studio) (1.3.3)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from chart_studio) (1.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->chart_studio) (8.0.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->chart_studio) (2.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests->chart_studio) (2.0.11)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->chart_studio) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->chart_studio) (2021.10.8)

구글 드라이브에서 '데이콘-집값 예측하기 대회' 데이터 파일을 가져오기위해 아래의 코드를 실행시킨다.

In [ ]:
# 구글 드라이브 연동코드
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 데이터 구성

### **1. train.csv : 학습 데이터**

id : 데이터 고유 id

OverallQual : 전반적 재료와 마감 품질

YearBuilt : 완공 연도

YearRemodAdd : 리모델링 연도

ExterQual : 외관 재료 품질

BsmtQual : 지하실 높이

TotalBsmtSF : 지하실 면적 

1stFlrSF : 1층 면적 

GrLivArea : 지상층 생활 면적

FullBath : 지상층 화장실 개수 

KitchenQual : 부억 품질 

GarageYrBlt : 차고 완공 연도

GarageCars: 차고 자리 개수

GarageArea: 차고 면적 

target : 집값(달러 단위)

### **2.test.csv**

id : 데이터 고유 id

OverallQual : 전반적 재료와 마감 품질

YearBuilt : 완공 연도

YearRemodAdd : 리모델링 연도

ExterQual : 외관 재료 품질

BsmtQual : 지하실 높이

TotalBsmtSF : 지하실 면적 

1stFlrSF : 1층 면적 

GrLivArea : 지상층 생활 면적

FullBath : 지상층 화장실 개수 

KitchenQual : 부억 품질 

GarageYrBlt : 차고 완공 연도

GarageCars: 차고 자리 개수

GarageArea: 차고 면적 


### **3.sample_submission.csv**


id : 데이터 고유 id

target : 집값(달러 단위)

코드 참고 : https://dacon.io/competitions/official/235869/codeshare/4267?page=1&dtype=recent

yun99님 코드 올려주셔서 감사합니다.

# DataLoad(데이터 불러오기)

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.backend_bases
import matplotlib.pyplot as plt
import plotly.express as px
import plotly
import warnings
warnings.filterwarnings('ignore')

train_data = pd.read_csv("/content/drive/MyDrive/housing/train.csv")
test_data = pd.read_csv("/content/drive/MyDrive/housing/test.csv")

/usr/local/lib/python3.7/dist-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)

# Data Check (데이터 확인)

In [ ]:
train_data.head()

   id  Overall Qual  Gr Liv Area  ... Year Remod/Add  Garage Yr Blt  target
0   1            10         2392  ...           2003           2003  386250
1   2             7         1352  ...           2007           2006  194000
2   3             5          900  ...           1967           1967  123000
3   4             5         1174  ...           2006           2000  135000
4   5             7         1958  ...           2005           2005  250000

[5 rows x 15 columns]

In [ ]:
test_data .head()

   id  Overall Qual  Gr Liv Area  ... Year Built  Year Remod/Add  Garage Yr Blt
0   1             9         1800  ...       2007            2007           2007
1   2             6         1082  ...       1948            1950           1948
2   3             6         1573  ...       2000            2000           2000
3   4             6         2443  ...       2004            2004           2004
4   5             5         1040  ...       1968            1968           1991

[5 rows x 14 columns]

In [ ]:
train_data.shape

(1350, 15)

In [ ]:
test_data.shape

(1350, 14)

In [ ]:
train_data['Bsmt Qual'].value_counts()

TA    605
Gd    582
Ex    134
Fa     28
Po      1
Name: Bsmt Qual, dtype: int64

In [ ]:
train_data['Exter Qual'].value_counts()

TA    808
Gd    485
Ex     49
Fa      8
Name: Exter Qual, dtype: int64

In [ ]:
train_data['Overall Qual'].value_counts()

5     379
6     351
7     307
8     156
4      75
9      56
10     15
3       8
2       3
Name: Overall Qual, dtype: int64

# Visualization(시각화)

여기서 부터는 'Kaggle'을 참고하여 '시각화'를 진행하였다.

In [ ]:
fig = px.histogram(train_data,x="Year Remod/Add", y="Year Built")
fig.show()

데이터는 'train' 데이터 값을 가져왔고, X축이 리모델링연도 y축이 완공연도를
 
의미한다.

In [ ]:
fig = px.histogram(test_data,x="Year Remod/Add", y="Year Built")
fig.show()

데이터는 'test' 데이터 값을 가져왔고, X축이 리모델링연도 y축이 완공연도를
 
의미한다.

In [ ]:
fig.update_layout(
    font_family="Courier New",
    font_color="blue",
    title_font_family="Times New Roman",
    title_font_color="red",
    legend_title_font_color="green"
)
fig.show()

데이터는 'train' 데이터를 가져왔고, x축이 집값, y축이 완공연도를 의미한다.

In [ ]:
fig = px.density_heatmap(train_data, x="target", y="Year Built",marginal_x="histogram", marginal_y="histogram")
fig.show()

데이터는 'train' 데이터를 가져왔고, x축이 집값, y축이 완공연도를 의미한다.

In [ ]:
ps = train_data.head(20)
from bubbly.bubbly import bubbleplot 
from plotly.offline import iplot
import chart_studio.plotly as py


figure = bubbleplot(dataset=ps, x_column='target', y_column='Year Built', 
    bubble_column='target', size_column='Year Built', color_column='target', 
    x_logscale=True, scale_bubble=2, height=300)

iplot(figure)

데이터는 'train_data'를 사용하였고 x 축은 '완공연도'를 의미하고 y 축은 '집값'을 의미한다.

In [ ]:
x = train_data['Year Built']
y = train_data['target']
fig = px.scatter(train_data, x, y, trendline="ols")
fig.show()

데이터는 'train_data'를 사용하였고 x축은 '리모델링 연도'를 의미하고 y축은 '집값'를 의미한다.

In [ ]:
x = train_data['Year Remod/Add']
y = train_data['Year Built']
fig = px.scatter(train_data, x, y, trendline="lowess")
fig.show()

데이터는 'train_data'를 사용하였고 x축은 '리모델링 연도'를 의미하고 y축은 '완공연도'를 의미한다.

In [ ]:
fig = px.scatter(train_data, x='Year Built', y='target',color='Year Built', trendline="ols")
fig.show()

데이터는 'trian_data'를 사용하였고, 'x'축은 '완공연도 'y'축은 '집값'을 의미한다.

# Data Cleanup(데이터 정리)
- 데이터를 보기 좋게 정리해준다.

In [ ]:
# 데이터 변수 순서 정리
cols1=['id', 'Year Built', 'Year Remod/Add', 'Garage Yr Blt',  'Overall Qual', 'Exter Qual', 'Bsmt Qual', 'Kitchen Qual', 'Gr Liv Area', 'Total Bsmt SF', '1st Flr SF', 'Garage Area', 'Full Bath', 'Garage Cars', 'target']
train_data=train_data[cols1]
cols2=['id', 'Year Built', 'Year Remod/Add', 'Garage Yr Blt',  'Overall Qual', 'Exter Qual', 'Bsmt Qual', 'Kitchen Qual', 'Gr Liv Area', 'Total Bsmt SF', '1st Flr SF', 'Garage Area', 'Full Bath', 'Garage Cars']
test_data=test_data[cols2]
train_data.head(3)

   id  Year Built  Year Remod/Add  ...  Full Bath  Garage Cars  target
0   1        2003            2003  ...          2            3  386250
1   2        2006            2007  ...          2            2  194000
2   3        1967            1967  ...          1            1  123000

[3 rows x 15 columns]

년도와 관련된 변수를 2022-변수로 바꿔준다.

In [ ]:
train_data['Year Built']=2022-train_data['Year Built']
train_data['Year Remod/Add']=2022-train_data['Year Remod/Add']
train_data['Garage Yr Blt']=2022-train_data['Garage Yr Blt']
test_data['Year Built']=2022-test_data['Year Built']
test_data['Year Remod/Add']=2022-test_data['Year Remod/Add']
test_data['Garage Yr Blt']=2022-test_data['Garage Yr Blt']

# Modelling(모델링)

## pycaret setup()(파이캐롯 셋업)
- 파이캐롯을 사용하기 위해 먼저 환경세팅을 해줍니다.

In [ ]:
def NMAE(true, pred): # NMAE의 경우 pycaret에서 지원하지 않습니다. 
    mae = np.mean(np.abs(true-pred))
    score = mae / np.mean(np.abs(true))
    return score

In [ ]:
from pycaret.classification import *
reg = setup(data = train_data,
            target = 'target',
            normalize=True,
            normalize_method='robust',
            data_split_shuffle = False, 
            create_clusters = False,
            use_gpu = True,
            silent = True,
            fold=10)

                               Description             Value
0                               session_id              8347
1                                   Target            target
2                              Target Type        Multiclass
3                            Label Encoded              None
4                            Original Data        (1350, 15)
5                           Missing Values             False
6                         Numeric Features                 8
7                     Categorical Features                 6
8                         Ordinal Features             False
9                High Cardinality Features             False
10                 High Cardinality Method              None
11                   Transformed Train Set         (944, 38)
12                    Transformed Test Set         (406, 38)
13                      Shuffle Train-Test             False
14                     Stratify Train-Test             False
15                          Fold Generator   StratifiedKFold
16                             Fold Number                10
17                                CPU Jobs                -1
18                                 Use GPU              True
19                          Log Experiment             False
20                         Experiment Name  clf-default-name
21                                     USI              fb49
22                         Imputation Type            simple
23          Iterative Imputation Iteration              None
24                         Numeric Imputer              mean
25      Iterative Imputation Numeric Model              None
26                     Categorical Imputer          constant
27  Iterative Imputation Categorical Model              None
28           Unknown Categoricals Handling    least_frequent
29                               Normalize              True
30                        Normalize Method            robust
31                          Transformation             False
32                   Transformation Method              None
33                                     PCA             False
34                              PCA Method              None
35                          PCA Components              None
36                     Ignore Low Variance             False
37                     Combine Rare Levels             False
38                    Rare Level Threshold              None
39                         Numeric Binning             False
40                         Remove Outliers             False
41                      Outliers Threshold              None
42                Remove Multicollinearity             False
43             Multicollinearity Threshold              None
44             Remove Perfect Collinearity              True
45                              Clustering             False
46                    Clustering Iteration              None
47                     Polynomial Features             False
48                       Polynomial Degree              None
49                    Trignometry Features             False
50                    Polynomial Threshold              None
51                          Group Features             False
52                       Feature Selection             False
53                Feature Selection Method           classic
54            Features Selection Threshold              None
55                     Feature Interaction             False
56                           Feature Ratio             False
57                   Interaction Threshold              None
58                           Fix Imbalance             False
59                    Fix Imbalance Method             SMOTE

## Compare_Model() (컴페어 모델)
- pycaret을 사용해서 각각 모델을 모두 비교하고 
  가장 적합한 모델을 적용해 준다.

In [ ]:
rf = create_model('rf', fold=5)

      Accuracy  AUC  Recall   Prec.      F1   Kappa     MCC    NMAE
0       0.0106  0.0  0.0077  0.0044  0.0062  0.0079  0.0080  0.1333
1       0.0053  0.0  0.0042  0.0026  0.0035  0.0014  0.0014  0.1269
2       0.0000  0.0  0.0000  0.0000  0.0000 -0.0034 -0.0034  0.1415
3       0.0053  0.0  0.0040  0.0053  0.0053  0.0019  0.0019  0.1607
4       0.0160  0.0  0.0117  0.0133  0.0142  0.0131  0.0131  0.1499
Mean    0.0074  0.0  0.0055  0.0051  0.0058  0.0042  0.0042  0.1425
SD      0.0054  0.0  0.0039  0.0045  0.0047  0.0057  0.0057  0.0119

In [ ]:
top =compare_models(sort = 'NMAE',n_select = 3, include = ['dt','lightgbm','rf'],fold=3)

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,NMAE,TT (Sec)
rf,Random Forest Classifier,0.0074,0.0,0.0047,0.0052,0.0059,0.0041,0.0041,0.1410,5.1133
lightgbm,Light Gradient Boosting Machine,0.0085,0.0,0.0047,0.0079,0.0077,0.0051,0.0052,0.1598,39.0667
dt,Decision Tree Classifier,0.0053,0.0,0.0027,0.0057,0.0047,0.0023,0.0023,0.1685,0.0767

## Blend Model (블렌드 모델)
- 모델을 합쳐준다.

In [ ]:
blender = blend_models(top,fold=3)
predict_model(blender)

      Accuracy  AUC  Recall   Prec.      F1   Kappa     MCC    NMAE
0       0.0000  0.0  0.0000  0.0000  0.0000 -0.0016 -0.0016  0.1577
1       0.0000  0.0  0.0000  0.0000  0.0000 -0.0031 -0.0031  0.1348
2       0.0211  0.0  0.0135  0.0105  0.0140  0.0179  0.0181  0.1172
3       0.0000  0.0  0.0000  0.0000  0.0000 -0.0033 -0.0034  0.1554
4       0.0106  0.0  0.0064  0.0106  0.0106  0.0082  0.0083  0.1492
5       0.0000  0.0  0.0000  0.0000  0.0000 -0.0034 -0.0034  0.1100
6       0.0000  0.0  0.0000  0.0000  0.0000 -0.0033 -0.0033  0.1148
7       0.0000  0.0  0.0000  0.0000  0.0000 -0.0031 -0.0031  0.1424
8       0.0106  0.0  0.0066  0.0053  0.0071  0.0072  0.0072  0.1616
9       0.0106  0.0  0.0063  0.0106  0.0106  0.0077  0.0078  0.1432
Mean    0.0053  0.0  0.0033  0.0037  0.0042  0.0023  0.0023  0.1386
SD      0.0071  0.0  0.0045  0.0048  0.0054  0.0071  0.0071  0.0178

               Model  Accuracy  AUC  Recall  ...      F1   Kappa     MCC    NMAE
0  Voting Classifier    0.0074    0  0.0037  ...  0.0066  0.0047  0.0047  0.1314

[1 rows x 9 columns]

IndexError: ignored

## Finalize Model(최종 모델)
- 최종 예측 모델과 예측 값을 출력한다.

In [ ]:
final_blend = finalize_model(blender)  
predict_model(final_blend)

               Model  Accuracy  AUC  Recall  ...     F1   Kappa     MCC    NMAE
0  Voting Classifier    0.9729    0  0.9588  ...  0.974  0.9728  0.9728  0.0017

[1 rows x 9 columns]

IndexError: ignored

# 방정식 만들기

In [ ]:
train_data.drop('id',axis=1,inplace=True)
test_data.drop('id',axis=1,inplace=True)

In [ ]:
# feature를 확인합니다.
train_data.columns

Index(['Year Built', 'Year Remod/Add', 'Garage Yr Blt', 'Overall Qual',
       'Exter Qual', 'Bsmt Qual', 'Kitchen Qual', 'Gr Liv Area',
       'Total Bsmt SF', '1st Flr SF', 'Garage Area', 'Full Bath',
       'Garage Cars', 'target'],
      dtype='object')

In [ ]:
# X와 Y를 각각 따로 저장합니다.
x_feature = 'Gr Liv Area'
y_feature = 'target'

X = train_data[x_feature]
Y = train_data[y_feature]

X

0       2392
1       1352
2        900
3       1174
4       1958
        ...
1345    1756
1346    2748
1347    1214
1348     894
1349     907
Name: Gr Liv Area, Length: 1350, dtype: int64

In [ ]:
import numpy as np

# 각각의 평균을 구합니다.
X_mean = np.mean(X)
Y_mean = np.mean(Y)

# 평균값을 이용하여 관계를 구합니다.
relation = Y_mean/X_mean

print(f"{x_feature}의 평균:{X_mean:.2f} \n{y_feature}의 평균:{Y_mean:.2f}")
print(f"따라서 {y_feature}는 {x_feature}의 평균 {relation:.2f}배 입니다.")
print(f"즉, a = {relation:.2f} 입니다.")
a = round(relation, 2)
print(f"업데이트 된 방정식 : Y = {a:.2f} * X + b")

Gr Liv Area의 평균:1513.54
target의 평균:186406.31
따라서 target는 Gr Liv Area의 평균 123.16배 입니다.
즉, a = 123.16 입니다.
업데이트 된 방정식 : Y = 123.16 * X + b

In [ ]:
# b = Y - a * X 를 그대로 작성합니다. 여기서도 평균값을 이용합니다.
b = Y_mean - a * X_mean

print(f"b는 {b:.2f} 입니다.")
print(f"업데이트 된 방정식 : Y = {a:.2f} * X + {b:.2f}")

b는 -1.55 입니다.
업데이트 된 방정식 : Y = 123.16 * X + -1.55

In [ ]:
predict_Y = a * X + b
predict_Y

0       294597.172504
1       166510.772504
2       110842.452504
3       144588.292504
4       241145.732504
            ...
1345    216267.412504
1346    338442.132504
1347    149514.692504
1348    110103.492504
1349    111704.572504
Name: Gr Liv Area, Length: 1350, dtype: float64

이 부분은 '데이콘 집값예측 경진대회'에서 코드를 제출하면 '리더보드'에서 순위를 결정 할 때 사용되는 수식이다.

In [ ]:
def NMAE(true, pred):
    mae = np.mean(np.abs(true-pred))
    score = mae / np.mean(np.abs(true))
    return score

In [ ]:
# 실제 정답 값을 준비합니다.
real_answer = Y.copy()

# 정답과 예측 값을 함수에 넣어 결과를 확인합니다.
error = NMAE(real_answer, predict_Y)

print(f"이 방정식의 평균 에러는 {error:.2f} 입니다.")

이 방정식의 평균 에러는 0.20 입니다.

출처 : https://dacon.io/competitions/official/235869/codeshare/4253?page=1&dtype=recent

# 최종 예측 및 제출

In [ ]:
# 예측하고자 하는 test 데이터를 불러옵니다.
test = pd.read_csv('/content/drive/MyDrive/housing/test.csv')

test.head()

   id  Overall Qual  Gr Liv Area  ... Year Built  Year Remod/Add  Garage Yr Blt
0   1             9         1800  ...       2007            2007           2007
1   2             6         1082  ...       1948            1950           1948
2   3             6         1573  ...       2000            2000           2000
3   4             6         2443  ...       2004            2004           2004
4   5             5         1040  ...       1968            1968           1991

[5 rows x 14 columns]

In [ ]:
# 예측의 재료를 가져옵니다.
test_X = test[x_feature]

# 예측을 진행합니다.
predict_test = a * test_X + b

# 예측 결과를 확인합니다.
predict_test

0       221686.452504
1       133257.572504
2       193729.132504
3       300878.332504
4       128084.852504
            ...
1345    237943.572504
1346    112320.372504
1347    106039.212504
1348    176117.252504
1349    287823.372504
Name: Gr Liv Area, Length: 1350, dtype: float64

In [ ]:
# 제출용 sample 파일을 불러옵니다.
submission = pd.read_csv('/content/drive/MyDrive/housing/sample_submission.csv')
submission.head()

   id  target
0   1       0
1   2       0
2   3       0
3   4       0
4   5       0

In [ ]:
# 위에서 구한 예측값을 그대로 넣어줍니다.
submission[y_feature] = predict_test

# 데이터가 잘 들어갔는지 확인합니다.
submission[y_feature] = predict_test

submission

        id         target
0        1  221686.452504
1        2  133257.572504
2        3  193729.132504
3        4  300878.332504
4        5  128084.852504
...    ...            ...
1345  1346  237943.572504
1346  1347  112320.372504
1347  1348  106039.212504
1348  1349  176117.252504
1349  1350  287823.372504

[1350 rows x 2 columns]

In [ ]:
# submission을 csv 파일로 저장합니다.
# index=False란 추가적인 id를 부여할 필요가 없다는 뜻입니다. 
# 정확한 채점을 위해 꼭 index=False를 넣어주세요.
submission.to_csv("submission.csv", index=False)